### PR TITLE
Fix device initialization

### PR DESCRIPTION
**Pull request by CaseySJ**
Provides a fix for Issue #58 to control both DC and PWM fan speeds on all 3 channels.

To speed up Merge Conflict resolution, I'll mention that the only change was the addition of Line #380 to `nzxt_smart_device.py`

Also, "Input/Output Error" on Windows will occur if CAM has been started. To prevent the I/O error, we must quit CAM GUI, but this still keeps several CAM background processes active. We must also terminate those processes manually from Task Manager.

### CODE REVIEW

**Comment by jonasmalacofilho** [comment]
Because git is distributed and you're not the only one working on this code, make sure your patch is based on the latest head of the master branch.

**Comment by CaseySJ** [comment]
You know, I spent a good 2 hours trying to rebase my fork, but in vain. GitHub is quite perplexing unless you have already figured out how it works. In the end I just issued a pull request. It’s just a 1-line change as I pointed out.

**Comment by jonasmalacofilho** [comment]
_Generally_ it's just a matter of `git rebase jonasmalacofilho/master` (from your feature branch, assuming the remote name for my repo is 'jonasmalacofilho', and that you've fetched it already).

However, it seems that there are so many merges and rebases that even GitHub's diff is getting confused (the diff shown for this pull request makes no sense; just finished reporting this to GitHub).  So while `rebase` would certainly get the job done, you could have to deal with conflicts and/or need to further clean the resulting branch of extraneous commits.

Because of that, and since we know exactly the only commit that should new to my 'master', I personally would probably simply reset and cherry-pick:

```
git checkout Fix-Device-Initialization    # start at your feature branch
git fetch jonasmalacofilho    # fetch my remote (adjust name if necessary)

git branch temp-backup    # backup this branch as is
git reset --hard jonasmalacofilho/master    # start fresh
git cherry-pick temp-backup    # cherry-pick the head of the backup/old branch
```

**Comment by jonasmalacofilho** [comment]
@CaseySJ 

> It’s just a 1-line change as I pointed out.

This pull request changes [much more than one line](https://github.com/jonasmalacofilho/liquidctl/compare/d6b3ed1a054b185c98d3d0d0aa328a1a9424fc39..8107eb3bea727f8e59aec100a6455087ee7cddaa).¹

---

¹ The normal [PR diff](https://github.com/jonasmalacofilho/liquidctl/pull/59/files) is bugged.

**Comment by CaseySJ** [comment]
I may have misunderstood the purpose of a `fork`. Would it be correct to say that if we just want to contribute to `jonasmalacofilho/liquidctl` instead of creating and maintaining a new derivative work, then we should just create development/patch branches from `jonasmalcofilho/liquidctl` itself?

This will allow the development/patch branch to be easily rebased to the original master, thereby making pull requests more seamless. Rebasing _across forks_ seems to be much more involved/problematic. So it seems `fork` is designed for creating a _derivative_ work rather than contributing to an existing work.

**Comment by jonasmalacofilho** [comment]
In general terms you're right that forks are not necessary for contributing patches a project.  You can simply clone the repository, make your changes, and send the resulting patches by email.

That said, the typical way to send patches in GitHub is through pull requests or, more specifically, GitHub pull requests (similar, but not the same thing as plain git pull requests).  The idea here is that you push your branch somewhere I have access to, and make a (machine readable) request that I pull in your code.

Specifically for GitHub pull requests, you need to have your own remote copy of the repository, with your own branches, in GitHub as well.  And that's what a GitHub fork is.

Now, GitHub forks can diverge or not.  In our case, I'm integrating all your changes so there probably isn't a good reason for you to keep a diverging fork (i.e. a fork in a more general sense).  And keeping a diverging fork involves cherry-picking fixes from upstream (me) as well as rebasing all your patches before sending them to me, which can amount to a substantial amount of work.

On the other hand, some examples of reasons to keep a diverging fork would be if the upstream repository wasn't receiving updates, if I didn't want to merge some of your changes, if you wanted to customize the output of the software for very specific uses cases, etc.

---

You'll want to work on a local repository on your machine.  You'll want to maintain a GitHub fork for you to sync your personal branches to.  Most of the time you'll be running the latest upstream code (or a stable version).   But, when a fix or new feature is necessary, you create a branch (from the latest upstream version) and develop and test your code there, syncing it to your fork.

Once the fix or feature is ready, you open a pull request for me to pull in that branch from your remote fork.  If there are any changes to be made, you can add more commits to and/or rewrite (aka rebase) the history of the branch.  And after the pull request is accepted and the code merged into upstream, you can go back to running the latest upstream code.

**Comment by jonasmalacofilho** [comment]
@CaseySJ 

I'm sure you have better things to do, so I'll just cherry-pick the necessary commit and close this.

---

To simplify your next pull requests I suggest you start by cloning my repository

```
git clone https://github.com/jonasmalacofilho/liquidctl
```

and running the latest code there.  If you have no local changes you'll be able to update with a simple `git pull`.

Then, when it's time for a new fix or feature, you can create a branch and add commits there:

```
git checkout --branch <branch-name>
git add [...]
git commit -v [...]
```

Pushing your branch to your fork involves adding a remote for it

```
git remote add <remote name> <remote git url>

# example (if you have ssh configured for github)
git remote add mine git@github.com:CaseySJ/liquidctl
```

and pushing your branch to it

```
git push --set-upstream <remote name> <branch name or HEAD for current branch>

# example
git push --set-upstream mine HEAD
```

**Feel free to ask for help if you have issues**.

And, by the way, a very good resource on git (if you have the time) is the [Pro Git](https://git-scm.com/book/en/v2) book, specially the first chapters.  I think that, given what I've seen you do here and in the hackintosh community, you will really enjoy and benefit from using git more extensively.

**Comment by CaseySJ** [comment]
You're quite right -- the [Pro Git](https://git-scm.com/book/en/v2) book is a wonderful tutorial. It's all making sense now!

**Pull request closed without merging**
