### PR TITLE
Create tutorial-macos.md

### PR DESCRIPTION
**Pull request by icedterminal**
Adding tutorial for installing on macOS systems.

### CODE REVIEW

**Comment by icedterminal** [comment]
The sample files currently link to a different repo, one for my hackintosh build. If preferred they can be added to this repo. Feel free to critique or edit what you want.

**Comment by jonasmalacofilho** [comment]
I'm nearly done with having both backends available on all platforms (defaulting to hidapi on Mac OS).  I'll review this once I finish that...

The launchd stuff is something I had already peaked at in your repo (from your reddit post, I think) and that I'll definitely be adding to the new "Automation" section of the README.

**Comment by jonasmalacofilho** [comment]
@icedterminal can you test the latest master branch?  If should have working hidapi + libusb support, and automatically pick the former on Mac OS.

**Comment by icedterminal** [comment]
Worked perfectly.

terminal

**Comment by jonasmalacofilho** [comment]
Thanks for the feedback.

As for the missing backend on Windows, the issue is that PyUSB is not finding the (proper) libusb libraries.  I see that you installed a _Python_ 'libusb' package, but, unfortunately, I have no idea what it does.

Instead, I recommend you [manually](https://github.com/jonasmalacofilho/liquidctl#system-dependencies) install the official libusb libraries.

Alternatively, you can also use the prebuilt `liquidctl.exe` from AppVeyor; it's built automatically from `./appveyor.yml` and already bundles the (official) libusb dlls.  Click on the green checkmark besides any (recent) commit and get the corresponding executable from the Artifacts tab.

---

<details>
<summary>Expand for my personal and (possibly unfair) first impressions of that package.</summary>

Let's take a look at its PyPI [listing](https://pypi.org/project/libusb/) and GitHub [repository](https://github.com/karpierz/libusb)...

> It is fully compliant implementation of the original C libusb 1.0 API by implementing whole its functionality in a clean Python instead of C.

Except that it [ships precompiled dlls](https://github.com/karpierz/libusb/tree/master/src/libusb/_platform/_windows/x64).

> Copyright (c) 2016-2018 Adam Karpierz

Except that the [first commit is from Aug 2017](https://github.com/karpierz/libusb/commits/master?after=0755dc25c60bfb92fa41dfe460c1b9fa638be913+34).

> Licensed under the zlib/libpng License

Except that [libusb is LGPL](https://github.com/libusb/libusb/blob/master/COPYING); depending on what exactly is in those opaque dlls, and what the rest of the package might do, there might be a licensing issue.

Finally, all commit messages are either version numbers or, _ipsis litteris,_ `...`.  [I'm not kidding.](https://github.com/karpierz/libusb/commits/master?before=0755dc25c60bfb92fa41dfe460c1b9fa638be913+35)

Maybe that package could solve the whole annoyance of installing libusb (proper) on Windows.  But it doesn't seem to play nice with PyUSB.  And, more importantly, it's, err... not confidence inspiring.

</details>

**Comment by icedterminal** [comment]
Well I'll just remove that one then. lol.

As for macOS, I simplified the [automation setup](https://github.com/icedterminal/ga-z270x-ug/blob/master/Post_Install/pump_control/SetupLiquidctl.sh). A simple script creates the files and then adds it to startup. Less for someone to do.

**Pull request merged**
