### PR TITLE
Add driver for Seasonic/NZXT E-series PSUs

### PR DESCRIPTION
**Pull request by jonasmalacofilho**
This is an initial attempt to support these PSUs.

Based on USB traffic capture by @jnettlet, the PMBus Spec (v1.3.1) and some guesswork.

Related: #31 ("Support for nzxt e series digital power supplies")

### CODE REVIEW

**Comment by jonasmalacofilho** [comment]
@jnettlet can you test this?

Only `liquidctl status` implemented so far... partially that is.

Please include the output with `--debug` even if everything miraculously (!) seems to work.

**Comment by jnettlet** [comment]
Ha...you beat me too it.  I just setup everything and did some additional
dumps to verify.  I believe most of your assumptions are correct.  I will
test this now.

**Comment by jnettlet** [comment]
`Device 1, NZXT E500 (experimental)
[DEBUG] liquidctl.driver.usb: replacing stock kernel driver with libusb
[DEBUG] liquidctl.driver.seasonic: write ad 00 03 01 60 8e (and 58 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 03 30 00 b5 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[ERROR] liquidctl.cli: Unexpected error
Traceback (most recent call last):
  File "/home/jnettlet/Source/git/liquidctl/liquidctl/cli.py", line 181, in _device_get_status
    status = dev.get_status(**kwargs)
  File "/home/jnettlet/Source/git/liquidctl/liquidctl/driver/seasonic.py", line 74, in get_status
    ('Temperature', self._get_float(CMD.READ_TEMPERATURE_2), '°C'),
  File "/home/jnettlet/Source/git/liquidctl/liquidctl/driver/seasonic.py", line 109, in _get_float
    return linear_to_float(self._exec_read(cmd, 2))
  File "/home/jnettlet/Source/git/liquidctl/liquidctl/driver/seasonic.py", line 98, in _exec_read
    assert ret[0:2] == [0xaa, data_len + 1]
AssertionError
[DEBUG] liquidctl.driver.usb: ensure interface is released
[DEBUG] liquidctl.driver.usb: restoring stock kernel driver
`

**Comment by jnettlet** [comment]
Here is a link to the latest clean capture.  [https://drive.google.com/open?id=1nuBrqeiRRjvkK7Y0QYBbKbnm1PJRcpwR](url)

**Comment by jnettlet** [comment]
Almost there.

`[jnettlet@mcbin-ws liquidctl]$ sudo liquidctl status -d 1 --debug
[DEBUG] liquidctl.cli: liquidctl v1.2.0rc4 (editable)
Device 1, NZXT E500 (experimental)
[DEBUG] liquidctl.driver.usb: replacing stock kernel driver with libusb
[DEBUG] liquidctl.driver.seasonic: write ad 00 03 01 60 8e (and 58 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 03 30 00 b5 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 03 01 60 90 (and 58 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 03 00 00 ef 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 03 04 60 06 02 00 20 (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 03 01 19 8f 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 00 8b (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 f4 05 e4 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 00 8c (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 1f c9 73 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 00 96 (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 56 db 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 03 04 60 06 02 01 20 (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 03 01 19 ed 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 01 8b (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 fc 05 65 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 01 8c (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 00 c8 c9 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 01 96 (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 00 c8 26 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 03 04 60 06 02 02 20 (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 03 01 19 4b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 02 8b (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 fd 05 0b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 02 8c (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 80 c8 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 02 96 (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 fe d2 d9 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 03 04 60 06 02 03 20 (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 03 01 19 29 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 03 8b (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 73 02 57 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 03 8c (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 17 c8 a7 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 03 96 (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 70 c8 d6 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 03 04 60 06 02 04 20 (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 03 01 19 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 04 8b (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 9d 01 14 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 04 8c (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 06 c8 3a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 04 96 (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 ff ff ff ff 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[ERROR] liquidctl.cli: Unexpected error
Traceback (most recent call last):
  File "/home/jnettlet/Source/git/liquidctl/liquidctl/cli.py", line 181, in _device_get_status
    status = dev.get_status(**kwargs)
  File "/home/jnettlet/Source/git/liquidctl/liquidctl/driver/seasonic.py", line 80, in get_status
    status.append((f'{name} output power', self._get_float(CMD.READ_POUT, page=i), 'W'))
  File "/home/jnettlet/Source/git/liquidctl/liquidctl/driver/seasonic.py", line 114, in _get_float
    return linear_to_float(self._exec_page_plus_read(page, cmd, 2))
  File "/home/jnettlet/Source/git/liquidctl/liquidctl/driver/seasonic.py", line 107, in _exec_page_plus_read
    assert ret[2] == data_len
AssertionError
[DEBUG] liquidctl.driver.usb: ensure interface is released
[DEBUG] liquidctl.driver.usb: restoring stock kernel driver
`

**Comment by jonasmalacofilho** [comment]
Hm, that one wasn't a false positive.  The PSU suddenly decided it didn't want to report power for the +3.3 V output rail.

Does this keep always happens at the same place?  Is there any chance something else is trying to talk to the PSU at the same time?

**Comment by jnettlet** [comment]
Nope it is only connected to a Linux box currently so is untouched.
Running again the failure happens in a different place.

**Comment by jonasmalacofilho** [comment]
Oh, so we probably just need some delays...  different place but still with READ_POUT, or different command too?

---

In the mean time, let me check if there's any "standard" value for this in the TI controller manual and/or the PMBus spec.  Though it's probably related to the custom PMBus-to-USB bridge...

**Comment by jnettlet** [comment]
`[jnettlet@mcbin-ws liquidctl]$ sudo liquidctl status -d 1 --debug
[DEBUG] liquidctl.cli: liquidctl v1.2.0rc4 (editable)
Device 1, NZXT E500 (experimental)
[DEBUG] liquidctl.driver.usb: replacing stock kernel driver with libusb
[DEBUG] liquidctl.driver.seasonic: write ad 00 03 01 60 8e (and 58 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 03 30 00 b5 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 03 01 60 90 (and 58 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 03 00 00 ef 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 03 04 60 06 02 00 20 (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 03 01 19 8f 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 00 8b (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 f5 05 f1 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 00 8c (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 1a c9 32 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 00 96 (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 47 db 46 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 03 04 60 06 02 01 20 (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 03 01 19 ed 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 01 8b (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 fd 05 70 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 01 8c (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 00 c8 c9 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 01 96 (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 00 c8 26 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 03 04 60 06 02 02 20 (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 03 01 19 4b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 02 8b (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 fd 05 0b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 02 8c (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 7f c8 d3 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 02 96 (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 f8 d2 a7 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 03 04 60 06 02 03 20 (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 03 01 19 29 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 03 8b (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 73 02 57 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 03 8c (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 17 c8 a7 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 03 96 (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 70 c8 d6 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 03 04 60 06 02 04 20 (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 03 01 19 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 04 8b (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 9d 01 14 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 04 8c (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 06 c8 3a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 04 04 60 06 02 04 96 (and 55 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 04 02 13 c8 c3 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[DEBUG] liquidctl.driver.seasonic: write ad 00 03 01 60 fc (and 58 padding bytes)
[DEBUG] liquidctl.driver.seasonic: received aa 03 11 41 d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Temperature                    48.0  °C
Fan speed                         0  rpm
+12V #1 output voltage        11.91  V
+12V #1 output current     2.203125  I
+12V #1 output power          26.22  W
+12V #2 output voltage        11.98  V
+12V #2 output current          0.0  I
+12V #2 output power           0.00  W
+12V #3 output voltage        11.98  V
+12V #3 output current    0.9921875  I
+12V #3 output power          11.88  W
+5V output voltage             4.90  V
+5V output current        0.1796875  I
+5V output power               0.88  W
+3.3V output voltage           3.23  V
+3.3V output current       0.046875  I
+3.3V output power             0.15  W
[DEBUG] liquidctl.driver.usb: ensure interface is released
[DEBUG] liquidctl.driver.usb: restoring stock kernel driver
`
Hurrah.  Although it took me three times running the command to get there.  So still some tweaking to do but on the right track.

**Comment by jonasmalacofilho** [comment]
> Although it took me three times running the command to get there.

Still randomly invalid responses?  Do you see any pattern in them, like if they are mostly in response to a particular command or something like that?  From now the only thing that occurs me is to increase the delay... or that blindly retrying when needed that is.  What do you think?

Another thing: can you easily spot which +12 V rail is which (CPU , "GPU"/PCI-e supplemental power, other)?

**Comment by jonasmalacofilho** [comment]
Yet another thing...

> ```
> [DEBUG] liquidctl.driver.seasonic: write ad 00 03 01 60 fc (and 58 padding bytes)
>                                                         ^^
> [DEBUG] liquidctl.driver.seasonic: received aa 03 11 41 d0 00 00 00 00 00 00 00 00 00 00 00 00 > 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
>                                                   ^^ ^^
> ```

I was obviously wrong about this MFR_SPECIFIC command being used for powered-on time.  But from all TI documents I saw it shouldn't be DEVICE_CODE either (in this particular family).  

Maybe it's (related to) the firmware version?  Can you check what version CAM reports?

Also, what's your current powered-on time as reported by CAM?

**Comment by jnettlet** [comment]
Firmware Revision is V40983.00
Power On is 2093h22m

**Comment by jnettlet** [comment]
Seems quite reliable now.  Nice work.

**Pull request merged**
